# Generated by Django 3.0.8 on 2020-07-31 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200728_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('total', models.FloatField()),
                ('createdDate', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='toppings',
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField()),
                ('toppings', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('size', models.CharField(max_length=50)),
                ('productName', models.CharField(max_length=90)),
                ('total', models.FloatField()),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='orders.OrderMain')),
            ],
        ),
    ]
