# Generated by Django 3.0.8 on 2020-07-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200731_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
