# Generated by Django 3.0.8 on 2020-07-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderdetails_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermain',
            name='userid',
            field=models.CharField(max_length=50),
        ),
    ]
