# Generated by Django 3.0.8 on 2020-08-02 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200731_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
        migrations.RenameModel(
            old_name='OrderMain',
            new_name='OrderMaster',
        ),
    ]
