# Generated by Django 3.0.8 on 2020-08-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200802_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='toppings',
            field=models.IntegerField(default=0),
        ),
    ]
